### ISSUE TITLE
content-inject: changing the source content doesn't get updated where it's been injected until you save that page

### ISSUE THREAD

**Issue by desertmonkey** [getgrav/grav-plugin-page-inject#17]
Hi,
I'm testing out Grav as a documentation tool, and the content-inject plugin looks perfect for us to reuse content. However, I noticed this issue: 

1. I create a page to use as content to be injected on other pages (the source page)
1. I then reference the source page content on another page using [ plugin:content-inject ] (TITLE)
1. The content shows up as expected on the other page. 
1. I make an edit to the source page. 
1. I refresh the other page, and the change isn't reflected. 
1. I then edit the other page and save, and the content that was injected finally appears. 

I disabled Processed Content, but this didn't make a difference. 

Thank you for looking into this! 

Pete

**Comment by rhukster** [comment]
This is purely related to caching.  When you use this plugin the page content is processed and (including any plugins that run on that content) and cached.  However, that said, Grav has a very simple cache busting strategy, any time any page is changed, it should flush all the page caches, and the page content is rebuilt.  So this 'should' work without any issue. 

I would maybe look at the cache **check method** configuration in the system.yaml, and if it's `folder` try changing that to `file` or you could even try `hash`.  Basically this is the mechanism Grav uses to determine if page cache has changed.

More info: https://learn.getgrav.org/basics/grav-configuration#cache

**Comment by desertmonkey** [comment]
Thank you @rhukster for the really fast reply! I tried changing the cache method to all the options (it was set to file, but I tried folder, hash and none), and they all behaved the same way. The Grav doc you linked doesn't discuss all the options, like the driver for example, so I tried changing it to file from auto to see what would happen, also without success.

Anything else you can think of? Thanks again. 

```
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: g
  clear_images_by_default: true
  cli_compatibility: false
  lifetime: 604800
  gzip: false
  allow_webserver_gzip: false
  redis:
    socket: false
```
